Extend view and cell templates
thefuntasty/MVVM-C-Templates pull request #33
Opened 2019-01-26 15:29 UTC by mikolasstuchlik

This pull request expands views and cell templates.

Motivation: Templates lack commonly used patterns like stand alone view or collection view elements. 

Updates:
* Add view template for Nibable protocol under FuntastyKit
* Add CollectionView Cell and Reusable views under CellKit/UIKit
* Rename Cell to TableCell
* Set default iPhone as iPhone X (iphone5_9) across modified templates
* Add template origin notice to source file headers across modified templates
* Add safe area margins by default across modified templates

[Regression warning]: I've made a mistake during development. I've started my work on outdated versions. I've already removed a lot of unwanted regression, but I ask reviewers to kindly seek for any remaining regression.

2019-01-31 09:29 UTC, mkj-is requested changes

2019-01-31 09:29 UTC, mkj-is commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>This generates a new collection view cell view under CellKit.</string>
I think the second `view` is redundant there.

```suggestion
	<string>This generates a new collection view cell under CellKit.</string>
```

2019-01-31 09:29 UTC, mkj-is commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>Collection Cell</string>
I prefer something like `CellKit Collection View Cell.xctemplate` so it is clear and the naming is consistent with other templates (even if it's longer). Also the names in comments should be the same as the name of the template.

```suggestion
	<string>CellKit Collection View Cell</string>
```

Sadly, this name is not what is showing in the list of templates in Xcode.

2019-01-31 09:29 UTC, mkj-is commented on CollectionCell.xctemplate/___VARIABLE_sourceCellIdentifier___CollectionCell.swift
> +//  Created by ___FULLUSERNAME___ on ___DATE___ using Collection View Cellkit Template (v1.0).
Also, CellKit has large K. 🙂

```suggestion
//  Created by ___FULLUSERNAME___ on ___DATE___ using CellKit Collection View Cell Template (v1.0).
```

2019-01-31 09:29 UTC, mkj-is commented on CollectionCell.xctemplate/___VARIABLE_sourceCellIdentifier___CollectionCellModel.swift
> +//  Created by ___FULLUSERNAME___ on ___DATE___ using Collection View Cellkit Template (v1.0).
```suggestion
//  Created by ___FULLUSERNAME___ on ___DATE___ using CellKit Collection View Cell Template (v1.0).
```

2019-01-31 09:29 UTC, mkj-is commented on CollectionReusableView.xctemplate/___VARIABLE_sourceViewIdentifier___CollectionReusableView.swift
> +final class ___VARIABLE_sourceViewIdentifier___CollectionReusableView: UICollectionReusableView {
Similar file can be created using the `Cocoa Touch Class` template. Basically, the only difference is the `final` keyword. I think this don't belong to our templates.

2019-01-31 09:29 UTC, mkj-is commented on TableCell.xctemplate/TemplateInfo.plist
> +	<string>This generates a new table cell view for CellKit.</string>
This order of words is more traditional due to the name of the superclass.

```suggestion
	<string>This generates a new table view cell for CellKit.</string>
```

2019-01-31 12:47 UTC, mikolasstuchlik commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>Collection Cell</string>
I see your point, but I think, that this name is way too long. Also, I think, that the CellKit is redundant and inconsistent. I would object, why our other templates does not contain similar prefixes (for example: FuntastyKitCoordinator, FuntastyKitViewModel etc.). I'm fine with the word "View".

2019-01-31 12:50 UTC, mikolasstuchlik commented on CollectionReusableView.xctemplate/___VARIABLE_sourceViewIdentifier___CollectionReusableView.swift
> +final class ___VARIABLE_sourceViewIdentifier___CollectionReusableView: UICollectionReusableView {
While developing Angelcam, I found out, that I spend time by creating files and naming them consistently. This template reduces amount of time people spend by searching for typos in multiple gaps across multiple files. However, if you don't consider this template as something worth merging, I'm fine with forking this repository and having this template separate. :)

2019-01-31 12:50 UTC, mkj-is commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>Collection Cell</string>
Next step is dividing these templates into the frameworks, so we can lose the framework prefixes then.

2019-01-31 12:55 UTC, mikolasstuchlik commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>Collection Cell</string>
:(

2019-01-31 12:58 UTC, mikolasstuchlik commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>Collection Cell</string>
But still, there will be some files created by this template by the time we divide this repo and those files won't be affected, so there will be some files with 5-7 words long names, which I consider a bit unfortunate.

2019-01-31 13:01 UTC, mikolasstuchlik commented on CollectionReusableView.xctemplate/___VARIABLE_sourceViewIdentifier___CollectionReusableView.swift
> +final class ___VARIABLE_sourceViewIdentifier___CollectionReusableView: UICollectionReusableView {
The Nibable protocol requires specific naming of multiple files and classes. There I see the difference between stock template and this one.

2019-02-07 13:21 UTC, mikolasstuchlik commented on CollectionCell.xctemplate/TemplateInfo.plist
> +	<string>Collection Cell</string>
I totally missed your point. I thought you want the CellKit string in name of files. Silly me.

2019-02-08 09:55 UTC, mkj-is commented on CellKit/TableViewHeaderFooter.xctemplate/___VARIABLE_sourceCellIdentifier___TableViewHeaderFooter.swift
> +        // Arbitary configuration here
Tento komentář bych dal pryč, myslím si, že je to dost jasné i bez něj.

2019-02-08 09:55 UTC, mkj-is commented on MVVM-C/NibableView.xctemplate/___VARIABLE_sourceViewIdentifier___View.swift
> +        // Arbitrary configuration here.
Tento komentář bych taky dal pryč.

2019-02-08 09:55 UTC, mkj-is commented on Makefile
> +TEMPLATE_NAMES = 'MVVM-C' 'CellKit'
Nešlo by to nějak zjednodušit a vzít všechny `*/*.xctemplate` soubory a zkopírovat je?

2019-02-08 11:00 UTC, mkj-is approved these changes

2019-02-08 11:00 UTC, merged